### ISSUE TITLE
Missing(?) conversions in _p2smap

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/osc-ingest-tools#1]
In https://github.com/os-climate/osc-ingest-tools/blob/main/osc_ingest_trino/sqltypes.py `_p2smap` does not have a translation for the `object` dtype.  Is it intentional to force upstream users to convert dtype to str before converting to SQL, or should we support `object` as a `varchar`?

Similarly, `_p2smap` does not support `datetime64[ns]`.  Should upstream users be forced to do everything relative to UTC?  Or should we allow unconverted timestamps?  Or should we perform some kind of conversion which, if there is no local timezone variable set, throws the appropriate exception so that the upstream user can properly initialize their local timezone so that the ingest tools can convert the data as needed?

**Comment by erikerlandson** [comment]
If we can come up with a plausible default for `object` then I'd be OK with assigning it.  Alternatively, I can support an additional parameter where the user can supply additional mappings.

I am also fine with assigning something to `datetime64[ns]`.  The current mappings, and any missing mappings, do not represent any "policy" - the intent is to add new mappings as they become relevant.

**Comment by erikerlandson** [comment]
It is best practice to use the `convert_dtypes()` pandas DF method, so that pandas data types can be made as specific as possible.

However I have filed #3 to address the likely use case of occasionally needing to either add new mappings, or override existing mappings.

**Comment by erikerlandson** [comment]
This should be now be fixable using the new `typemap` parameter to `create_table_schema_pairs`:
https://github.com/os-climate/osc-ingest-tools#adding-custom-type-mappings-to-create_table_schema_pairs

**Comment by MichaelTiemannOSC** [comment]
Indeed.  I'll take it from here.
