### ISSUE TITLE
ingest_unmanaged_parquet litters /tmp with .parquet files

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/osc-ingest-tools#11]
For debugging purposes, I can see why one might want to have a parquet file in /tmp to examine, but none of the utils files clean up WORKDIR after operation, leading to lots of litter collecting in /tmp.  I think we need a better garbage collector than "just go into the shell and remove all the dead .parquet files in /tmp".

**Comment by erikerlandson** [comment]
closing this - see #14
