### ISSUE TITLE
Update osc-ingest-tools for Iceberg-based ingestion

### ISSUE THREAD

**Issue by caldeirav** [os-climate/osc-ingest-tools#13]
The tools require updating to reflect the architectural and operational decision to use Iceberg at the data layer and drive ingestion through SQL Alchemy / data frame interactions. This means that we need to:

- [x] Add the custom insertion method for batch ingestion as per the example: https://github.com/os-climate/data-platform-demo/blob/master/notebooks/trino-iceberg-demo.ipynb (fulfilled by #15)
- [x] Remove deprecated function drop_unmanaged_table / drop_unmanaged_data, ingest_unmanaged_parquet, unmanaged_parquet_tabledef that were based on parquet-based ingestion in Trino. (addressed by #14)
- [x] Review the usefulness of sqlcols / sqltypes functions with the new approach

**Comment by erikerlandson** [comment]
Definitely want to add the new custom insert.

I feel unsure about removing other deprecated methods, although I agree that in a world with no hive connector they serve no purpose. In the new platform clusters, our plan is to never expose S3 credentials for any trino-owned buckets, so the risk of keeping "unmanaged" family of methods is low.

agree that sqlcols/sqltypes may not be relevant in an iceberg world.  I am wondering what our convention there should be.  One has to create a table (initially empty) before injecting any data from a pandas or other tabular source - what mechanisms should we use here?  In theory it is still possible to drive new table schema from the column types of a pandas dataframe, but that may not be the best methodology to use in defining table schema.  Table creation may become a "special" operation, but what is the best way to execute it, so the record of it is durable?

**Comment by caldeirav** [comment]
Can we then at least find a way to indicate these methods as deprecated (doc) then?

On the convention problem, my thought was:
- When we ingest, we may or may not have format for the source
- If a format for the source is specified, it could make sense to go with a table creation then loading the data. So having a table creation method that takes as an input the table definition metadata could make sense and simplify / standardise the process.
- In the case the source format is not specified, I would go with default types for the loading, with the expectation that the transformation / distribution pipeline would anyway be the one "deciding" about the format (potentially based on other sources having to be merged). In our proposed approach we would not modify the ingestion schema but rather create intermediate and distribution tables in Trino.

What do you think?

**Comment by erikerlandson** [comment]
I will remove "unmanaged" methods - if we need a "safety valve" for using these, then the solution will be to use `osc-ingest-tools<=0.2.1`

My intuition about defining table schemas is that it is somewhat decoupled from actual ingest - we'll not want to "accidentally" alter table schema.  In theory I might be able to create github actions to detect certain kinds of specialized issues to create or updat schemas - then any such creation is by definition gated and recorded on github.  Regardless, I will for now keep sqlcols/sqltypes just in case.

**Comment by erikerlandson** [comment]
The new version is `osc-ingest-tools==0.3.0`
