### ISSUE TITLE
Should sqlalchemy-trino be deprecated, replaced with sqlqalchemy[trino]?

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/osc-ingest-tools#31]
Reading the docs at the GitHub pages for sqlalchemy-trino, it appears that the good bits have either been migrated up to sqlalchemy or trino and made available as sqlalchemy[trino].  See https://pypi.org/project/sqlalchemy-trino/ (which says `sqlalchemy-trino was developed as [Trino](https://trino.io/) (f.k.a PrestoSQL) dialect for SQLAlchemy. Since trinodb/trino-python-client#81, all code of sqlalchemy-trino is donated and merged into upstream project. So now, this project is no longer active and consider as deprecated.`) and https://github.com/trinodb/trino-python-client.

TIMESTAMP support in Trino/Iceberg remains very problematic, but we should filter out the confusion that an extra layer of sqlalchemy-trino may add.

**Comment by erikerlandson** [comment]
@MichaelTiemannOSC   we should come up with a testing plan for this.   I can create a testing version of osc-ingest-tools (publish to pypi testing site), that uses `sqlqalchemy[trino]`, and we can see if your notebooks operate properly.  You will also want to make sure that `sqlalchemy-trino` is fully uninstalled from your environment.

**Comment by MichaelTiemannOSC** [comment]
Indeed, because installing osc-ingest-tools presented re-installs `sqlalchemy-trino` it takes extra work to remove it.  Having done that, the first thing I did to make things work for ingestion was to change the visit_TIMESTAMP code (bottom of compiler.py in the Trino dialect subdirectory) to return TIMESTAMP(6) instead of TIMESTAMP.  But that's a blunt instrument for working with Iceberg and will break other Trino connectors that need TIMESTAMP(3) (the current alias for TIMESTAMP).

**Comment by erikerlandson** [comment]
@MichaelTiemannOSC  the following "dev" version remove `sqlalchemy-trino` and instead uses `sqlalchemy[trino]`
https://pypi.org/project/osc-ingest-tools/0.4.0.dev1/

**Comment by MichaelTiemannOSC** [comment]
Funny story: sqlalchemy-trino is a pre-requisite for connecting SuperSet to Trino.  I need to update my Docker's YML file...

**Comment by MichaelTiemannOSC** [comment]
Update to the funny story above: SuperSet version 2.0 has migrated away from sqlalchemy-trino: https://github.com/apache/superset/pull/19957
