### ISSUE TITLE
pull forward the file -> hive utilities from v0.2.1

### ISSUE THREAD

**Issue by erikerlandson** [os-climate/osc-ingest-tools#35]
Using `df.to_sql()` with `TrinoBatchInsert` does not scale to large files.  Using `df -> hive -> iceberg` is 70x faster in my testing. So I am going to resurrect the old `unmanaged` utilities from v0.2.1

**Comment by erikerlandson** [comment]
cc @MichaelTiemannOSC  @caldeirav

**Comment by caldeirav** [comment]
Agree and I suggest if possible we adopt some better naming conventions that reflect the two ingestion models:

- df.to_sql() in my view will be used mostly at scale for the event-driven ingestion pattern (https://github.com/os-climate/os_c_data_commons/blob/main/docs/add-data-pipeline-ingestion-patterns-event.md) where typically a service will aggregate a few hundred records for ongoing insertion into a partitioned typically historical table.
- the hive to iceberg approach should be primarily used for batch level insert of an entire data set at once.

@MichaelTiemannOSC any idea on good naming that will help and not confuse the users who work with the data?

**Comment by MichaelTiemannOSC** [comment]
Various pandas readers and writers have `engine=` and `storage=` parameters.  One idea would be to rely on the user to guide what is the appropriate method/strategy.  Or we could use a `.size` threshold to activate hive/parquet when size > 500 or so.
