### ISSUE TITLE
Fast ingest not quite working with typemap={'datetime64[ns]':'timestamp'}

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/osc-ingest-tools#37]
I get this error when I use timestamp or timestamp(3) (parquet's millisecond preference).  I get a different error when I used timestamp(6) (iceberg's millisecond preference).

2022-08-16 15:57:51,941 [517] INFO     trino.client: <Response [204]>
---------------------------------------------------------------------------
TrinoQueryError                           Traceback (most recent call last)
File /opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py:1824, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1822 context.post_exec()
-> 1824 result = context._setup_result_proxy()
   1826 if not self._is_future:

File /opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/default.py:1424, in DefaultExecutionContext._setup_result_proxy(self)
   1423 if self.is_crud or self.is_text:
-> 1424     result = self._setup_dml_or_text_result()
   1425 else:

File /opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/default.py:1506, in DefaultExecutionContext._setup_dml_or_text_result(self)
   1502     strategy = _cursor.BufferedRowCursorFetchStrategy(
   1503         self.cursor, self.execution_options
   1504     )
   1505 cursor_description = (
-> 1506     strategy.alternate_cursor_description or self.cursor.description
   1507 )
   1508 if cursor_description is None:

File /opt/app-root/lib64/python3.8/site-packages/trino/dbapi.py:266, in Cursor.description(self)
    264 @property
    265 def description(self):
--> 266     if self._query.columns is None:
    267         return None

File /opt/app-root/lib64/python3.8/site-packages/trino/client.py:736, in TrinoQuery.columns(self)
    733     while not self._columns and not self.finished and not self.cancelled:
    734         # Columns don't return immediate after query is summited.
    735         # Continue fetching data until columns are available and push fetched rows into buffer.
--> 736         self._result._rows += self.fetch()
    737 return self._columns

File /opt/app-root/lib64/python3.8/site-packages/trino/client.py:791, in TrinoQuery.fetch(self)
    790 response = self._request.get(self._request.next_uri)
--> 791 status = self._request.process(response)
    792 self._update_state(status)

File /opt/app-root/lib64/python3.8/site-packages/trino/client.py:536, in TrinoRequest.process(self, http_response)
    535 if "error" in response:
--> 536     raise self._process_error(response["error"], response.get("id"))
    538 if constants.HEADER_CLEAR_SESSION in http_response.headers:

TrinoQueryError: TrinoQueryError(type=INTERNAL_ERROR, name=PROCEDURE_CALL_FAILED, message="java.net.URISyntaxException: Relative path in absolute URI: year=2017-01-01 00:00:00.000000000", query_id=20220816_155751_01406_xh647)

The above exception was the direct cause of the following exception:

DBAPIError                                Traceback (most recent call last)
Input In [31], in <cell line: 1>()
----> 1 create_trino_table_and_dbt_metadata('ghg_data', essd_data_df, "array['year']", custom_meta_content, custom_meta_fields)

Input In [30], in create_trino_table_and_dbt_metadata(tablename, df, partitioning, custom_meta_content, custom_meta_fields, verbose)
     38     else:
     39         # ??? FIX THIS LATER
     40         partition_columns = None
---> 42     osc.fast_pandas_ingest_via_hive(
     43         df,
     44         engine,
     45         iceberg_catalog, iceberg_schema, iceberg_table,
     46         hive_bucket, ingest_catalog, ingest_schema,
     47         partition_columns = partition_columns,
     48         overwrite = True,
     49         typemap={'datetime64[ns]':'timestamp(3)'},
     50         verbose = True
     51     )
     53     with open(f"/opt/app-root/src/essd-ingest-pipeline/dbt/essd_transform/models/{iceberg_table}.sql", "w", encoding="utf-8") as f:
     54         print("{{ config(materialized='table') }}" + f"""
     55 
     56 with source_data as (
   (...)
     61 select * from source_data
     62 """, file=f)

File /opt/app-root/lib64/python3.8/site-packages/osc_ingest_trino/trino_utils.py:115, in fast_pandas_ingest_via_hive(df, engine, catalog, schema, table, hive_bucket, hive_catalog, hive_schema, partition_columns, overwrite, typemap, colmap, verbose)
    113     print("\nsyncing partition metadata on intermediate hive table")
    114 sql = text(f"call {hive_catalog}.system.sync_partition_metadata('{hive_schema}', '{hive_table}', 'FULL')")
--> 115 _do_sql(sql, engine, verbose=verbose)
    117 if overwrite:
    118     if verbose:

File /opt/app-root/lib64/python3.8/site-packages/osc_ingest_trino/trino_utils.py:49, in _do_sql(sql, engine, verbose)
     47 if verbose:
     48     print(sql)
---> 49 qres = engine.execute(sql)
     50 res = qres.fetchall()
     51 if verbose:

File <string>:2, in execute(self, statement, *multiparams, **params)

File /opt/app-root/lib64/python3.8/site-packages/sqlalchemy/util/deprecations.py:401, in _decorate_with_warning.<locals>.warned(fn, *args, **kwargs)
    399 if not skip_warning:
    400     _warn_with_version(message, version, wtype, stacklevel=3)
--> 401 return fn(*args, **kwargs)

File /opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py:3152, in Engine.execute(self, statement, *multiparams, **params)
   3134 """Executes the given construct and returns a
   3135 :class:`_engine.CursorResult`.
   3136 
   (...)
   3149 
   3150 """
   3151 connection = self.connect(close_with_result=True)
-> 3152 return connection.execute(statement, *multiparams, **params)

File /opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py:1295, in Connection.execute(self, statement, *multiparams, **params)
   1291     util.raise_(
   1292         exc.ObjectNotExecutableError(statement), replace_context=err
   1293     )
   1294 else:
-> 1295     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)

File /opt/app-root/lib64/python3.8/site-packages/sqlalchemy/sql/elements.py:325, in ClauseElement._execute_on_connection(self, connection, multiparams, params, execution_options, _force)
    321 def _execute_on_connection(
    322     self, connection, multiparams, params, execution_options, _force=False
    323 ):
    324     if _force or self.supports_execution:
--> 325         return connection._execute_clauseelement(
    326             self, multiparams, params, execution_options
    327         )
    328     else:
    329         raise exc.ObjectNotExecutableError(self)

File /opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py:1487, in Connection._execute_clauseelement(self, elem, multiparams, params, execution_options)
   1475 compiled_cache = execution_options.get(
   1476     "compiled_cache", self.engine._compiled_cache
   1477 )
   1479 compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
   1480     dialect=dialect,
   1481     compiled_cache=compiled_cache,
   (...)
   1485     linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
   1486 )
-> 1487 ret = self._execute_context(
   1488     dialect,
   1489     dialect.execution_ctx_cls._init_compiled,
   1490     compiled_sql,
   1491     distilled_params,
   1492     execution_options,
   1493     compiled_sql,
   1494     distilled_params,
   1495     elem,
   1496     extracted_params,
   1497     cache_hit=cache_hit,
   1498 )
   1499 if has_events:
   1500     self.dispatch.after_execute(
   1501         self,
   1502         elem,
   (...)
   1506         ret,
   1507     )

File /opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py:1851, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1848             branched.close()
   1850 except BaseException as e:
-> 1851     self._handle_dbapi_exception(
   1852         e, statement, parameters, cursor, context
   1853     )
   1855 return result

File /opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py:2032, in Connection._handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   2030     util.raise_(newraise, with_traceback=exc_info[2], from_=e)
   2031 elif should_wrap:
-> 2032     util.raise_(
   2033         sqlalchemy_exception, with_traceback=exc_info[2], from_=e
   2034     )
   2035 else:
   2036     util.raise_(exc_info[1], with_traceback=exc_info[2])

File /opt/app-root/lib64/python3.8/site-packages/sqlalchemy/util/compat.py:207, in raise_(***failed resolving arguments***)
    204     exception.__cause__ = replace_context
    206 try:
--> 207     raise exception
    208 finally:
    209     # credit to
    210     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    211     # as the __traceback__ object creates a cycle
    212     del exception, replace_context, from_, with_traceback

File /opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/base.py:1824, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1813     self.dispatch.after_cursor_execute(
   1814         self,
   1815         cursor,
   (...)
   1819         context.executemany,
   1820     )
   1822 context.post_exec()
-> 1824 result = context._setup_result_proxy()
   1826 if not self._is_future:
   1827     should_close_with_result = branched.should_close_with_result

File /opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/default.py:1424, in DefaultExecutionContext._setup_result_proxy(self)
   1422 def _setup_result_proxy(self):
   1423     if self.is_crud or self.is_text:
-> 1424         result = self._setup_dml_or_text_result()
   1425     else:
   1426         strategy = self.cursor_fetch_strategy

File /opt/app-root/lib64/python3.8/site-packages/sqlalchemy/engine/default.py:1506, in DefaultExecutionContext._setup_dml_or_text_result(self)
   1501 if self._is_server_side and strategy is _cursor._DEFAULT_FETCH:
   1502     strategy = _cursor.BufferedRowCursorFetchStrategy(
   1503         self.cursor, self.execution_options
   1504     )
   1505 cursor_description = (
-> 1506     strategy.alternate_cursor_description or self.cursor.description
   1507 )
   1508 if cursor_description is None:
   1509     strategy = _cursor._NO_CURSOR_DML

File /opt/app-root/lib64/python3.8/site-packages/trino/dbapi.py:266, in Cursor.description(self)
    264 @property
    265 def description(self):
--> 266     if self._query.columns is None:
    267         return None
    269     # [ (name, type_code, display_size, internal_size, precision, scale, null_ok) ]

File /opt/app-root/lib64/python3.8/site-packages/trino/client.py:736, in TrinoQuery.columns(self)
    732 if self.query_id:
    733     while not self._columns and not self.finished and not self.cancelled:
    734         # Columns don't return immediate after query is summited.
    735         # Continue fetching data until columns are available and push fetched rows into buffer.
--> 736         self._result._rows += self.fetch()
    737 return self._columns

File /opt/app-root/lib64/python3.8/site-packages/trino/client.py:791, in TrinoQuery.fetch(self)
    789 """Continue fetching data for the current query_id"""
    790 response = self._request.get(self._request.next_uri)
--> 791 status = self._request.process(response)
    792 self._update_state(status)
    793 logger.debug(status)

File /opt/app-root/lib64/python3.8/site-packages/trino/client.py:536, in TrinoRequest.process(self, http_response)
    534 logger.debug("HTTP %s: %s", http_response.status_code, response)
    535 if "error" in response:
--> 536     raise self._process_error(response["error"], response.get("id"))
    538 if constants.HEADER_CLEAR_SESSION in http_response.headers:
    539     for prop in get_header_values(
    540         http_response.headers, constants.HEADER_CLEAR_SESSION
    541     ):

DBAPIError: (trino.exceptions.TrinoQueryError) TrinoQueryError(type=INTERNAL_ERROR, name=PROCEDURE_CALL_FAILED, message="java.net.URISyntaxException: Relative path in absolute URI: year=2017-01-01 00:00:00.000000000", query_id=20220816_155751_01406_xh647)
[SQL: call osc_datacommons_hive_ingest.system.sync_partition_metadata('ingest', 'ingest_temp_37167c90', 'FULL')]
(Background on this error at: https://sqlalche.me/e/14/dbapi)

**Comment by erikerlandson** [comment]
Not sure if it's directly impacting your problem but `partition_columns` should default to `[]` (empty array), not `None`, although python's promiscuous typing might allow `len(None)` to work.

**Comment by erikerlandson** [comment]
@MichaelTiemannOSC  what stage of the ingest is this happening in?   Is it happening during the `insert` command where the hive table is inserted into iceberg?  Or somewhere else? `verbose=True` may help here, if you aren't already setting it

**Comment by MichaelTiemannOSC** [comment]
This is happening after the data has been staged to parquet and the _do_sql command is attempting to align the hive parquet files with the hive parquet table.  It looks like somehow a timestamp field is not being quoted (?) and being misinterpreted as a URI??

**Comment by erikerlandson** [comment]
This appears to be a problem with trino not handling its own partition sync.  I posted a question about it over on trino slack (`#troubleshooting`)

**Comment by erikerlandson** [comment]
@MichaelTiemannOSC   are you partitioning by the timestamps?

**Comment by erikerlandson** [comment]
@MichaelTiemannOSC   so IIUC you have `timestamp()` structures that are representing years: `year=2017-01-01 00:00:00.000000000`

If I'm right about what's going on, it will work much better if you just store actual year values, as integers or strings. "2017" or integer 2017, etc.

I can look into some more advanced trino system calls, but also, storing simple year is likely to be more efficient than an actual timestamp in this case.

**Comment by MichaelTiemannOSC** [comment]
Roger that.  Adjusting pd.read_excel parameters to avoid producing timestamp.  HOWEVER, SuperSet gets mad when you have a time series that doesn't have a datatime related to time (you can adjust manually setting a value to be temporal).  I wish these two components could work out their differences at meet each other half-way ;-)

**Comment by erikerlandson** [comment]
Will superset work with `date` ?

**Comment by erikerlandson** [comment]
to-do note: investigate `hive.timestamp-precision` configuration to see if it makes the hive/iceberg representation align better

**Comment by MichaelTiemannOSC** [comment]
OK, from experiments last night and this morning, I've learned a few things.  On the Trino/hive/iceberg side, when partitioning on a column, the column needs to have values that make for nice filenames.  Partitioning on a datetime (or a date, which becomes a datetime when one touches it) is problematic because the values look like "YYY-MM-DD HH:MM:SS.XXXYYY" where XXX are milliseconds (in hive) and YYY are additionally microseconds (in Trino).  The space and the colon present all sorts of interpretation problems between what data is stored in the column and how partitioning functions.

Reading https://trino.io/episodes/5.html it becomes clear that dates of the form YYYY-MM-DD want to be varchars which can be converted to DATE when querying if and when actual date functionality is needed.  Of course we don't need to convert to dates to do equality testing, sort order, aggregation, etc.  Only when we need to start doing math.  If we think we're going to be doing a lot of math, not the simple stuff, we should make the column a datetime and we should not partition on it.

Finally, the fast ingestion mode needs to work with tables that are not partitioned.  When partition_columns==[], there's no need to sync partition metadata.  I'll file an issue for that.

**Comment by MichaelTiemannOSC** [comment]
This problem was fixed by properly configuring the hive.timestamp-precision parameter.
