### ISSUE TITLE
fast_pandas_ingest_via_hive fails for non-partitioned tables

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/osc-ingest-tools#38]
The https://github.com/os-climate/data-platform-demo/blob/master/notebooks/trino-hive-iceberg-ingest.ipynb notebook demonstrates a fast path for loading dataframes into iceberg via hive.  But it only demonstrates the functionality for a table with a single partition (an int64 year).  https://github.com/os-climate/osc-ingest-tools/issues/37 concerns the problems of partitioning on a datetime (or a date) year column.

This issue concerns using the fast path for loading a dataframe that is not partitioned.  In such a case an error is thrown:

`ProgrammingError: (trino.exceptions.TrinoUserError) TrinoUserError(type=USER_ERROR, name=INVALID_PROCEDURE_ARGUMENT, message="Table is not partitioned: ingest.ingest_temp_1cd0680f", query_id=20220816_232223_01460_xh647)
[SQL: call osc_datacommons_hive_ingest.system.sync_partition_metadata('ingest', 'ingest_temp_1cd0680f', 'FULL')]`

the call is at line 114:

`    sql = text(f"call {hive_catalog}.system.sync_partition_metadata('{hive_schema}', '{hive_table}', 'FULL')")`

My guess is that this call should be conditional on whether len(partition_columns)>0.

**Comment by erikerlandson** [comment]
Wow, that is annoying.  Yes, it will need to be conditional on a nonzero partition array.

**Comment by MichaelTiemannOSC** [comment]
I can understand why, in C++, you'd want to force programmers to do all kinds of tests in advance before calling a function (gotta count those CPU cycles), but I think it's more pythonic to be liberal if what one accepts and conservative in what one requires.
