### ISSUE TITLE
Dataframe with datetime64[ns, UTC] is not ingestible

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/osc-ingest-tools#7]
I have a dataframe that I've coerced to have a datetime that osc_ingest_trino understands:

sankey_data = [
    ['direct emitters', 'parent_attribution', 1],
    ['suppliers', 'parent_attribution', 2],
    ['parent_attribution', 'CO2e', 3],
    ['parent_attribution', 'LEI', 4],
    ['sec sub', '10-k', 5],
    ['sec sub', 'LEI', 6],
    ['sec sub', 'SIC', 7],
    ['sec num', '10-k', 8],
    ['10-k', 'revenue', 9],
    ['revenue', 'intensity', 0],
    ['CO2e', 'intensity', 1],
    ['intensity', 'company intensity', 2],
    ['intensity', 'sector intensity', 3],
    ['LEI', 'company intensity', 4],
    ['SIC', 'sector intensity', 5],    
]

df = pd.DataFrame(data=sankey_data, columns=('source', 'target', 'qty'))

df['year'] = pd.to_datetime("2020-01-01")
df = df.convert_dtypes()
df.year = df.year.astype('datetime64[ns, UTC]')

I get this error message:

TrinoUserError: TrinoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Incorrect timestamp precision for timestamp(6); the configured precision is MILLISECONDS", query_id=20211208_224842_00491_kx99a)

I get a different error message if don't do the manual conversion:

ValueError: unexpected pandas column type 'datetime64[ns]'

I'd like to be able to create a dataframe that contains date values.

**Comment by erikerlandson** [comment]
Out of curiosity, have you tried giving `create_table_schema_pairs` an override to use `timestamp(3)` ?

**Comment by MichaelTiemannOSC** [comment]
Have not.  I have in the past manually copied in that code and made a change, but haven't tried override syntax.  Will have a look at that.


Michael


________________________________

**Comment by MichaelTiemannOSC** [comment]
unmanaged_parquet_tabledef interface does not allow me to override the typemap.  For now I've made a local copy of that function where I can add my own typemap.  But this is not a good long-term fix.
