### ISSUE TITLE
query engine for catalog and schema parameters?

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/osc-ingest-tools#9]
I have a use case where I need to be able to query the engine to know what the default catalog and schema are.  This works when I set the catalog and schema as part of the sqlargs string.  I don't know that it works by simply using those strings to set the path as to where the data will be found.  Perhaps this does work, but what would be great is documentation that says how we can get information we set at initialization.

**Comment by erikerlandson** [comment]
You should already be able to do this:
https://github.com/os-climate/osc-ingest-tools/blob/main/osc_ingest_trino/trino_utils.py#L10

Use the `catalog="catalog_name"` and `schema="schema_name"` kw args

**Comment by erikerlandson** [comment]
can we close this, or do you need something different?

**Comment by MichaelTiemannOSC** [comment]
Just to be clear, the goal was to get the catalog and schema values from an initialized engine.  I've lost the handle on which notebook needed to get that info so will close this and re-report if I find it necessary again.
